use crate::provider::{LLMProviderTrait, LLMRequest, SuggestedTask};
use serde::{Deserialize, Serialize};

/// Maximum number of context entries to keep in memory
pub const MAX_CONTEXT_ENTRIES: usize = 100;

/// Configuration for the CodeAgent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    /// Maximum number of iterations to attempt
    pub max_iterations: u32,
    /// Maximum tokens per LLM request
    pub max_tokens_per_request: Option<usize>,
    /// Timeout in seconds for each request
    pub timeout_seconds: u64,
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 60,
        }
    }
}

/// Result from executing a task through the CodeAgent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResult {
    /// Content generated by the agent
    pub content: String,
    /// Total tokens used
    pub tokens_used: u32,
    /// Tasks suggested by the agent
    pub suggested_tasks: Vec<SuggestedTask>,
    /// New context entries generated
    pub new_context: Vec<String>,
    /// Commands executed during task execution
    pub commands_executed: Vec<String>,
}

/// Main agent for executing code generation tasks
#[allow(dead_code)]
pub struct CodeAgent {
    /// LLM provider for generating responses
    provider: Box<dyn LLMProviderTrait>,
    /// Agent configuration
    config: AgentConfig,
}

impl CodeAgent {
    /// Create a new CodeAgent with the specified LLM provider and config
    ///
    /// # Arguments
    /// * `provider` - LLM provider implementation
    /// * `config` - Agent configuration
    ///
    /// # Returns
    /// New CodeAgent instance
    pub fn new(provider: Box<dyn LLMProviderTrait>, config: AgentConfig) -> Self {
        Self { provider, config }
    }

    /// Execute a task with the given PRD and context
    ///
    /// This is a stub implementation that builds the LLM request structure.
    /// Full task execution logic will be implemented in a future task.
    ///
    /// # Arguments
    /// * `prd` - Product Requirements Document
    /// * `task` - Current task description
    /// * `context` - Previous context/iterations
    ///
    /// # Returns
    /// Result containing AgentResult or error
    pub async fn execute_task(
        &self,
        prd: String,
        task: String,
        context: Vec<String>,
    ) -> anyhow::Result<AgentResult> {
        let _request = LLMRequest {
            prd,
            task,
            context,
            max_tokens: self.config.max_tokens_per_request,
        };

        Ok(AgentResult {
            content: String::new(),
            tokens_used: 0,
            suggested_tasks: vec![],
            new_context: vec![],
            commands_executed: vec![],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mocks::MockLLMProvider;

    #[test]
    fn test_max_context_entries_constant() {
        assert_eq!(MAX_CONTEXT_ENTRIES, 100);
    }

    #[test]
    fn test_agent_config_default() {
        let config = AgentConfig::default();
        assert_eq!(config.max_iterations, 10);
        assert_eq!(config.max_tokens_per_request, Some(4000));
        assert_eq!(config.timeout_seconds, 60);
    }

    #[test]
    fn test_agent_config_custom() {
        let config = AgentConfig {
            max_iterations: 20,
            max_tokens_per_request: Some(8000),
            timeout_seconds: 120,
        };
        assert_eq!(config.max_iterations, 20);
        assert_eq!(config.max_tokens_per_request, Some(8000));
        assert_eq!(config.timeout_seconds, 120);
    }

    #[test]
    fn test_agent_config_serialization() {
        let config = AgentConfig {
            max_iterations: 5,
            max_tokens_per_request: Some(2000),
            timeout_seconds: 30,
        };

        let json = serde_json::to_string(&config).unwrap();
        let deserialized: AgentConfig = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.max_iterations, config.max_iterations);
        assert_eq!(
            deserialized.max_tokens_per_request,
            config.max_tokens_per_request
        );
        assert_eq!(deserialized.timeout_seconds, config.timeout_seconds);
    }

    #[test]
    fn test_code_agent_new_creates_instance() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let _agent = CodeAgent::new(provider, config);

        assert!(true);
    }

    #[tokio::test]
    async fn test_execute_task_builds_correct_request() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig {
            max_iterations: 5,
            max_tokens_per_request: Some(2000),
            timeout_seconds: 30,
        };

        let agent = CodeAgent::new(provider, config);

        let prd = "Build a web server".to_string();
        let task = "Create HTTP handler".to_string();
        let context = vec![
            "Iteration 1: Set up project structure".to_string(),
            "Iteration 2: Added dependencies".to_string(),
        ];

        let result = agent
            .execute_task(prd.clone(), task.clone(), context.clone())
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();

        assert!(agent_result.content.is_empty());
        assert_eq!(agent_result.tokens_used, 0);
        assert!(agent_result.suggested_tasks.is_empty());
        assert!(agent_result.new_context.is_empty());
        assert!(agent_result.commands_executed.is_empty());
    }

    #[test]
    fn test_agent_result_default() {
        let result = AgentResult {
            content: "Test content".to_string(),
            tokens_used: 500,
            suggested_tasks: vec![],
            new_context: vec![],
            commands_executed: vec![],
        };

        assert_eq!(result.content, "Test content");
        assert_eq!(result.tokens_used, 500);
        assert!(result.suggested_tasks.is_empty());
        assert!(result.new_context.is_empty());
        assert!(result.commands_executed.is_empty());
    }

    #[test]
    fn test_agent_result_serialization() {
        let result = AgentResult {
            content: "Generated code".to_string(),
            tokens_used: 1000,
            suggested_tasks: vec![SuggestedTask {
                title: "Add tests".to_string(),
                description: "Write unit tests".to_string(),
                priority: 5,
            }],
            new_context: vec!["Iteration 1: Created handler".to_string()],
            commands_executed: vec!["cargo build".to_string()],
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: AgentResult = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.content, result.content);
        assert_eq!(deserialized.tokens_used, result.tokens_used);
        assert_eq!(
            deserialized.suggested_tasks.len(),
            result.suggested_tasks.len()
        );
        assert_eq!(deserialized.new_context.len(), result.new_context.len());
        assert_eq!(
            deserialized.commands_executed.len(),
            result.commands_executed.len()
        );
    }

    #[test]
    fn test_agent_config_without_max_tokens() {
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: None,
            timeout_seconds: 60,
        };

        assert!(config.max_tokens_per_request.is_none());
    }

    #[tokio::test]
    async fn test_execute_task_with_empty_context() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a CLI tool".to_string(),
                "Implement command parsing".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_execute_task_with_full_context() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let agent = CodeAgent::new(provider, config);

        let context = (0..MAX_CONTEXT_ENTRIES)
            .map(|i| format!("Iteration {}: Did something", i + 1))
            .collect();

        let result = agent
            .execute_task(
                "Complex project".to_string(),
                "Final task".to_string(),
                context,
            )
            .await;

        assert!(result.is_ok());
    }

    #[test]
    fn test_max_context_entries_is_usize() {
        let _max: usize = MAX_CONTEXT_ENTRIES;
        assert_eq!(_max, 100);
    }
}
