use crate::provider::{LLMProviderTrait, LLMRequest, SuggestedTask};
use serde::{Deserialize, Serialize};
use tracing::warn;

/// Error types for agent operations
#[derive(thiserror::Error, Debug)]
pub enum AgentError {
    #[error("LLM request timed out after {0} seconds")]
    Timeout(u64),
    #[error("LLM provider error: {0}")]
    ProviderError(#[from] anyhow::Error),
}

/// Maximum number of context entries to keep in memory
pub const MAX_CONTEXT_ENTRIES: usize = 100;

/// Configuration for the CodeAgent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    /// Maximum number of iterations to attempt
    pub max_iterations: u32,
    /// Maximum tokens per LLM request
    pub max_tokens_per_request: Option<usize>,
    /// Timeout in seconds for each request
    pub timeout_seconds: u64,
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 60,
        }
    }
}

/// Result from executing a task through the CodeAgent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResult {
    /// Content generated by the agent
    pub content: String,
    /// Total tokens used
    pub tokens_used: u32,
    /// Tasks suggested by the agent
    pub suggested_tasks: Vec<SuggestedTask>,
    /// New context entries generated
    pub new_context: Vec<String>,
    /// Commands executed during task execution
    pub commands_executed: Vec<String>,
}

/// Main agent for executing code generation tasks
#[allow(dead_code)]
pub struct CodeAgent {
    /// LLM provider for generating responses
    provider: Box<dyn LLMProviderTrait>,
    /// Agent configuration
    config: AgentConfig,
}

impl CodeAgent {
    /// Create a new CodeAgent with the specified LLM provider and config
    ///
    /// # Arguments
    /// * `provider` - LLM provider implementation
    /// * `config` - Agent configuration
    ///
    /// # Returns
    /// New CodeAgent instance
    pub fn new(provider: Box<dyn LLMProviderTrait>, config: AgentConfig) -> Self {
        Self { provider, config }
    }

    /// Build truncated context from full context history
    ///
    /// Implements FIFO truncation when context exceeds MAX_CONTEXT_ENTRIES.
    /// Keeps the most recent N entries, discarding the oldest first.
    ///
    /// # Arguments
    /// * `context` - Full context history
    ///
    /// # Returns
    /// Truncated context vector (may be same as input if no truncation needed)
    fn build_truncated_context(&self, context: Vec<String>) -> Vec<String> {
        if context.len() <= MAX_CONTEXT_ENTRIES {
            context
        } else {
            let original_len = context.len();
            let truncated: Vec<String> = context
                .into_iter()
                .rev()
                .take(MAX_CONTEXT_ENTRIES)
                .collect::<Vec<_>>()
                .into_iter()
                .rev()
                .collect();

            warn!(
                "Context truncated from {} to {} entries (dropped {} oldest entries)",
                original_len,
                MAX_CONTEXT_ENTRIES,
                original_len - MAX_CONTEXT_ENTRIES
            );

            truncated
        }
    }

    /// Execute a task with the given PRD and context
    ///
    /// This is a stub implementation that builds the LLM request structure.
    /// Full task execution logic will be implemented in a future task.
    ///
    /// # Arguments
    /// * `prd` - Product Requirements Document
    /// * `task` - Current task description
    /// * `context` - Previous context/iterations
    ///
    /// # Returns
    /// Result containing AgentResult or error
    pub async fn execute_task(
        &self,
        prd: String,
        task: String,
        context: Vec<String>,
    ) -> Result<AgentResult, AgentError> {
        let truncated_context = self.build_truncated_context(context);

        let request = LLMRequest {
            prd,
            task,
            context: truncated_context,
            max_tokens: self.config.max_tokens_per_request,
        };

        let timeout_duration = tokio::time::Duration::from_secs(self.config.timeout_seconds);

        let llm_response = tokio::time::timeout(timeout_duration, self.provider.complete(&request))
            .await
            .map_err(|_| AgentError::Timeout(self.config.timeout_seconds))??;

        Ok(AgentResult {
            content: llm_response.content,
            tokens_used: llm_response.tokens_used,
            suggested_tasks: llm_response.suggested_tasks,
            new_context: vec![],
            commands_executed: llm_response.commands,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mocks::MockLLMProvider;

    #[test]
    fn test_max_context_entries_constant() {
        assert_eq!(MAX_CONTEXT_ENTRIES, 100);
    }

    #[test]
    fn test_agent_config_default() {
        let config = AgentConfig::default();
        assert_eq!(config.max_iterations, 10);
        assert_eq!(config.max_tokens_per_request, Some(4000));
        assert_eq!(config.timeout_seconds, 60);
    }

    #[test]
    fn test_agent_config_custom() {
        let config = AgentConfig {
            max_iterations: 20,
            max_tokens_per_request: Some(8000),
            timeout_seconds: 120,
        };
        assert_eq!(config.max_iterations, 20);
        assert_eq!(config.max_tokens_per_request, Some(8000));
        assert_eq!(config.timeout_seconds, 120);
    }

    #[test]
    fn test_agent_config_serialization() {
        let config = AgentConfig {
            max_iterations: 5,
            max_tokens_per_request: Some(2000),
            timeout_seconds: 30,
        };

        let json = serde_json::to_string(&config).unwrap();
        let deserialized: AgentConfig = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.max_iterations, config.max_iterations);
        assert_eq!(
            deserialized.max_tokens_per_request,
            config.max_tokens_per_request
        );
        assert_eq!(deserialized.timeout_seconds, config.timeout_seconds);
    }

    #[test]
    fn test_code_agent_new_creates_instance() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let _agent = CodeAgent::new(provider, config);
    }

    #[tokio::test]
    async fn test_execute_task_builds_correct_request() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig {
            max_iterations: 5,
            max_tokens_per_request: Some(2000),
            timeout_seconds: 30,
        };

        let agent = CodeAgent::new(provider, config);

        let prd = "Build a web server".to_string();
        let task = "Create HTTP handler".to_string();
        let context = vec![
            "Iteration 1: Set up project structure".to_string(),
            "Iteration 2: Added dependencies".to_string(),
        ];

        let result = agent
            .execute_task(prd.clone(), task.clone(), context.clone())
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();

        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
        assert_eq!(agent_result.tokens_used, 100);
        assert!(agent_result.suggested_tasks.is_empty());
        assert!(agent_result.new_context.is_empty());
        assert!(agent_result.commands_executed.is_empty());
    }

    #[test]
    fn test_agent_result_default() {
        let result = AgentResult {
            content: "Test content".to_string(),
            tokens_used: 500,
            suggested_tasks: vec![],
            new_context: vec![],
            commands_executed: vec![],
        };

        assert_eq!(result.content, "Test content");
        assert_eq!(result.tokens_used, 500);
        assert!(result.suggested_tasks.is_empty());
        assert!(result.new_context.is_empty());
        assert!(result.commands_executed.is_empty());
    }

    #[test]
    fn test_agent_result_serialization() {
        let result = AgentResult {
            content: "Generated code".to_string(),
            tokens_used: 1000,
            suggested_tasks: vec![SuggestedTask {
                title: "Add tests".to_string(),
                description: "Write unit tests".to_string(),
                priority: 5,
            }],
            new_context: vec!["Iteration 1: Created handler".to_string()],
            commands_executed: vec!["cargo build".to_string()],
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: AgentResult = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.content, result.content);
        assert_eq!(deserialized.tokens_used, result.tokens_used);
        assert_eq!(
            deserialized.suggested_tasks.len(),
            result.suggested_tasks.len()
        );
        assert_eq!(deserialized.new_context.len(), result.new_context.len());
        assert_eq!(
            deserialized.commands_executed.len(),
            result.commands_executed.len()
        );
    }

    #[test]
    fn test_agent_config_without_max_tokens() {
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: None,
            timeout_seconds: 60,
        };

        assert!(config.max_tokens_per_request.is_none());
    }

    #[tokio::test]
    async fn test_execute_task_with_empty_context() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a CLI tool".to_string(),
                "Implement command parsing".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();
        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
    }

    #[tokio::test]
    async fn test_execute_task_with_full_context() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();

        let agent = CodeAgent::new(provider, config);

        let context = (0..MAX_CONTEXT_ENTRIES)
            .map(|i| format!("Iteration {}: Did something", i + 1))
            .collect();

        let result = agent
            .execute_task(
                "Complex project".to_string(),
                "Final task".to_string(),
                context,
            )
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();
        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
    }

    #[test]
    fn test_max_context_entries_is_usize() {
        let _max: usize = MAX_CONTEXT_ENTRIES;
        assert_eq!(_max, 100);
    }

    #[tokio::test]
    async fn test_timeout_is_enforced() {
        let provider = Box::new(
            MockLLMProvider::new().with_delay(2000), // 2 second delay
        );
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 1, // 1 second timeout
        };

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a web server".to_string(),
                "Create HTTP handler".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), AgentError::Timeout(1)));
    }

    #[tokio::test]
    async fn test_normal_completion_does_not_timeout() {
        let provider = Box::new(
            MockLLMProvider::new().with_delay(100), // 100ms delay
        );
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 1, // 1 second timeout
        };

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a web server".to_string(),
                "Create HTTP handler".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();
        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
    }

    #[tokio::test]
    async fn test_timeout_error_message() {
        let provider = Box::new(MockLLMProvider::new().with_delay(6000)); // 6 second delay
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 5, // 5 second timeout
        };

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a web server".to_string(),
                "Create HTTP handler".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_err());
        let error = result.unwrap_err();
        let error_msg = format!("{}", error);
        assert!(error_msg.contains("timed out"));
        assert!(error_msg.contains("5"));
    }

    #[tokio::test]
    async fn test_custom_timeout_from_config() {
        let provider = Box::new(MockLLMProvider::new().with_delay(1500));
        let config = AgentConfig {
            max_iterations: 10,
            max_tokens_per_request: Some(4000),
            timeout_seconds: 2, // 2 second timeout
        };

        let agent = CodeAgent::new(provider, config);

        let result = agent
            .execute_task(
                "Build a web server".to_string(),
                "Create HTTP handler".to_string(),
                vec![],
            )
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();
        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
    }

    #[test]
    fn test_context_truncation_works_correctly() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        // Create context with 150 entries (exceeds MAX_CONTEXT_ENTRIES of 100)
        let context: Vec<String> = (1..=150).map(|i| format!("Entry {}", i)).collect();

        let truncated = agent.build_truncated_context(context);

        // Should keep only last 100 entries (51-150)
        assert_eq!(truncated.len(), 100);
        assert_eq!(truncated[0], "Entry 51");
        assert_eq!(truncated[99], "Entry 150");
    }

    #[test]
    fn test_warning_logged_when_truncated() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        // Create context with 120 entries
        let context: Vec<String> = (1..=120).map(|i| format!("Entry {}", i)).collect();

        // This should log a warning (we can't easily test logging output, but we verify truncation)
        let truncated = agent.build_truncated_context(context);

        assert_eq!(truncated.len(), 100);
        assert_eq!(truncated[0], "Entry 21");
        assert_eq!(truncated[99], "Entry 120");
    }

    #[test]
    fn test_small_context_not_truncated() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        // Create context with 50 entries (below MAX_CONTEXT_ENTRIES)
        let context: Vec<String> = (1..=50).map(|i| format!("Entry {}", i)).collect();

        let truncated = agent.build_truncated_context(context);

        // Should return same context without modification
        assert_eq!(truncated.len(), 50);
        assert_eq!(truncated[0], "Entry 1");
        assert_eq!(truncated[49], "Entry 50");
    }

    #[test]
    fn test_empty_context_not_truncated() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        let context: Vec<String> = vec![];
        let truncated = agent.build_truncated_context(context);

        assert_eq!(truncated.len(), 0);
    }

    #[test]
    fn test_exact_max_context_not_truncated() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        // Create context with exactly MAX_CONTEXT_ENTRIES
        let context: Vec<String> = (1..=MAX_CONTEXT_ENTRIES)
            .map(|i| format!("Entry {}", i))
            .collect();

        let truncated = agent.build_truncated_context(context.clone());

        // Should not be truncated
        assert_eq!(truncated.len(), MAX_CONTEXT_ENTRIES);
        assert_eq!(truncated[0], "Entry 1");
        assert_eq!(truncated[99], "Entry 100");
    }

    #[tokio::test]
    async fn test_execute_task_uses_truncated_context() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        // Create context with 150 entries
        let large_context: Vec<String> = (1..=150)
            .map(|i| format!("Iteration {}: Completed task", i))
            .collect();

        let result = agent
            .execute_task(
                "Build a web server".to_string(),
                "Create HTTP handler".to_string(),
                large_context,
            )
            .await;

        assert!(result.is_ok());
        let agent_result = result.unwrap();
        assert_eq!(
            agent_result.content,
            "Mock LLM response - for testing purposes"
        );
    }

    #[test]
    fn test_context_truncation_preserves_order() {
        let provider = Box::new(MockLLMProvider::new());
        let config = AgentConfig::default();
        let agent = CodeAgent::new(provider, config);

        let context: Vec<String> = (1..=200).map(|i| format!("Entry {}", i)).collect();

        let truncated = agent.build_truncated_context(context);

        // Should preserve original order of last 100 entries
        assert_eq!(truncated.len(), 100);
        for (i, entry) in truncated.iter().enumerate() {
            let expected_value = i + 101; // 101 to 200
            assert_eq!(entry, &format!("Entry {}", expected_value));
        }
    }
}
