use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Request sent to LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMRequest {
    /// Product Requirements Document
    pub prd: String,
    /// Current task to execute
    pub task: String,
    /// Previous context/iterations
    pub context: Vec<String>,
    /// Maximum tokens to generate
    pub max_tokens: Option<usize>,
}

/// Response from LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    /// Content generated by LLM
    pub content: String,
    /// Tokens used for this request
    pub tokens_used: u32,
    /// Tasks suggested by LLM to create
    pub suggested_tasks: Vec<SuggestedTask>,
    /// Commands extracted from LLM response
    pub commands: Vec<String>,
}

/// Suggested task from LLM response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuggestedTask {
    /// Task title
    pub title: String,
    /// Task description
    pub description: String,
    /// Task priority (higher = more important)
    pub priority: i32,
}

/// Trait for LLM provider implementations
#[async_trait]
pub trait LLMProviderTrait: Send + Sync {
    /// Complete a request to the LLM
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_request_serialization() {
        let request = LLMRequest {
            prd: "Build a web server".to_string(),
            task: "Create HTTP handler".to_string(),
            context: vec!["Previous task completed".to_string()],
            max_tokens: Some(1000),
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.prd, request.prd);
        assert_eq!(deserialized.task, request.task);
        assert_eq!(deserialized.context, request.context);
        assert_eq!(deserialized.max_tokens, request.max_tokens);
    }

    #[test]
    fn test_llm_response_serialization() {
        let response = LLMResponse {
            content: "Here's the code".to_string(),
            tokens_used: 500,
            suggested_tasks: vec![SuggestedTask {
                title: "Add tests".to_string(),
                description: "Write unit tests".to_string(),
                priority: 5,
            }],
            commands: vec!["cargo test".to_string()],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.content, response.content);
        assert_eq!(deserialized.tokens_used, response.tokens_used);
        assert_eq!(
            deserialized.suggested_tasks.len(),
            response.suggested_tasks.len()
        );
        assert_eq!(deserialized.commands.len(), response.commands.len());
    }

    #[test]
    fn test_suggested_task_serialization() {
        let task = SuggestedTask {
            title: "Fix bug".to_string(),
            description: "Fix the bug in handler".to_string(),
            priority: 10,
        };

        let json = serde_json::to_string(&task).unwrap();
        let deserialized: SuggestedTask = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.title, task.title);
        assert_eq!(deserialized.description, task.description);
        assert_eq!(deserialized.priority, task.priority);
    }

    #[test]
    fn test_llm_request_without_max_tokens() {
        let request = LLMRequest {
            prd: "Test".to_string(),
            task: "Task".to_string(),
            context: vec![],
            max_tokens: None,
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert!(deserialized.max_tokens.is_none());
    }

    #[test]
    fn test_empty_collections_in_response() {
        let response = LLMResponse {
            content: "Content".to_string(),
            tokens_used: 100,
            suggested_tasks: vec![],
            commands: vec![],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert!(deserialized.suggested_tasks.is_empty());
        assert!(deserialized.commands.is_empty());
    }
}
