use anthropic_rust::{Client, ContentBlock, Model};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Request sent to LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMRequest {
    /// Product Requirements Document
    pub prd: String,
    /// Current task to execute
    pub task: String,
    /// Previous context/iterations
    pub context: Vec<String>,
    /// Maximum tokens to generate
    pub max_tokens: Option<usize>,
}

/// Response from LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    /// Content generated by LLM
    pub content: String,
    /// Tokens used for this request
    pub tokens_used: u32,
    /// Tasks suggested by LLM to create
    pub suggested_tasks: Vec<SuggestedTask>,
    /// Commands extracted from LLM response
    pub commands: Vec<String>,
}

/// Suggested task from LLM response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuggestedTask {
    /// Task title
    pub title: String,
    /// Task description
    pub description: String,
    /// Task priority (higher = more important)
    pub priority: i32,
}

/// Trait for LLM provider implementations
#[async_trait]
pub trait LLMProviderTrait: Send + Sync {
    /// Complete a request to the LLM
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse>;
}

/// Anthropic Claude LLM provider
pub struct ClaudeProvider {
    client: Client,
}

impl ClaudeProvider {
    /// Create a new ClaudeProvider with an API key
    ///
    /// # Arguments
    /// * `api_key` - Anthropic API key
    pub fn new(api_key: String) -> anyhow::Result<Self> {
        let client = Client::builder()
            .api_key(&api_key)
            .model(Model::Claude35Sonnet20241022)
            .build()?;
        Ok(Self { client })
    }

    /// Build a system prompt from PRD and context
    fn build_system_prompt(&self, prd: &str, context: &[String]) -> String {
        let mut prompt = String::from("# Project PRD\n");
        prompt.push_str(prd);
        prompt.push_str("\n\n");

        if !context.is_empty() {
            prompt.push_str("# Context\n");
            for (i, ctx) in context.iter().enumerate() {
                prompt.push_str(&format!("## Iteration {}\n{}\n\n", i + 1, ctx));
            }
        }

        prompt
    }
}

#[async_trait]
impl LLMProviderTrait for ClaudeProvider {
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse> {
        let system_prompt = self.build_system_prompt(&request.prd, &request.context);

        let mut chat_builder = self.client.chat_builder().system(&system_prompt);

        for ctx in &request.context {
            chat_builder = chat_builder.user_message(ContentBlock::text(ctx));
        }

        chat_builder = chat_builder.user_message(ContentBlock::text(&request.task));

        let chat_request = chat_builder.build();
        let response = self.client.execute_chat(chat_request).await?;

        let content: String = response
            .content
            .iter()
            .filter_map(|block| {
                if let ContentBlock::Text { text, .. } = block {
                    Some(text.clone())
                } else {
                    None
                }
            })
            .collect();

        let tokens_used = response.usage.input_tokens + response.usage.output_tokens;

        Ok(LLMResponse {
            content,
            tokens_used,
            suggested_tasks: vec![],
            commands: vec![],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_request_serialization() {
        let request = LLMRequest {
            prd: "Build a web server".to_string(),
            task: "Create HTTP handler".to_string(),
            context: vec!["Previous task completed".to_string()],
            max_tokens: Some(1000),
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.prd, request.prd);
        assert_eq!(deserialized.task, request.task);
        assert_eq!(deserialized.context, request.context);
        assert_eq!(deserialized.max_tokens, request.max_tokens);
    }

    #[test]
    fn test_llm_response_serialization() {
        let response = LLMResponse {
            content: "Here's the code".to_string(),
            tokens_used: 500,
            suggested_tasks: vec![SuggestedTask {
                title: "Add tests".to_string(),
                description: "Write unit tests".to_string(),
                priority: 5,
            }],
            commands: vec!["cargo test".to_string()],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.content, response.content);
        assert_eq!(deserialized.tokens_used, response.tokens_used);
        assert_eq!(
            deserialized.suggested_tasks.len(),
            response.suggested_tasks.len()
        );
        assert_eq!(deserialized.commands.len(), response.commands.len());
    }

    #[test]
    fn test_suggested_task_serialization() {
        let task = SuggestedTask {
            title: "Fix bug".to_string(),
            description: "Fix the bug in handler".to_string(),
            priority: 10,
        };

        let json = serde_json::to_string(&task).unwrap();
        let deserialized: SuggestedTask = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.title, task.title);
        assert_eq!(deserialized.description, task.description);
        assert_eq!(deserialized.priority, task.priority);
    }

    #[test]
    fn test_llm_request_without_max_tokens() {
        let request = LLMRequest {
            prd: "Test".to_string(),
            task: "Task".to_string(),
            context: vec![],
            max_tokens: None,
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert!(deserialized.max_tokens.is_none());
    }

    #[test]
    fn test_empty_collections_in_response() {
        let response = LLMResponse {
            content: "Content".to_string(),
            tokens_used: 100,
            suggested_tasks: vec![],
            commands: vec![],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert!(deserialized.suggested_tasks.is_empty());
        assert!(deserialized.commands.is_empty());
    }

    #[test]
    fn test_claude_provider_build_system_prompt_with_context() {
        let provider =
            ClaudeProvider::new("sk-ant-api03-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a web server";
        let context = vec![
            "Iteration 1: Created HTTP handler".to_string(),
            "Iteration 2: Added authentication".to_string(),
        ];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a web server"));
        assert!(prompt.contains("# Context"));
        assert!(prompt.contains("Iteration 1: Created HTTP handler"));
        assert!(prompt.contains("Iteration 2: Added authentication"));
    }

    #[test]
    fn test_claude_provider_build_system_prompt_without_context() {
        let provider =
            ClaudeProvider::new("sk-ant-api03-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a CLI tool";
        let context = vec![];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a CLI tool"));
        assert!(!prompt.contains("# Context"));
    }

    #[tokio::test]
    #[ignore = "Requires ANTHROPIC_API_KEY environment variable"]
    async fn test_claude_provider_integration() {
        let api_key = std::env::var("ANTHROPIC_API_KEY")
            .expect("ANTHROPIC_API_KEY must be set for integration test");

        let provider = ClaudeProvider::new(api_key).unwrap();
        let request = LLMRequest {
            prd: "Build a simple calculator".to_string(),
            task: "What is 2 + 2?".to_string(),
            context: vec![],
            max_tokens: Some(100),
        };

        let result = provider.complete(&request).await.unwrap();

        assert!(!result.content.is_empty());
        assert!(result.tokens_used > 0);
        assert!(result.suggested_tasks.is_empty());
        assert!(result.commands.is_empty());
    }
}
