use anthropic_rust::{Client, ContentBlock, Model};
use async_openai::types::{ChatCompletionRequestMessage, CreateChatCompletionRequestArgs};
use async_openai::{Client as OpenAIClient, config::OpenAIConfig};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Request sent to LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMRequest {
    /// Product Requirements Document
    pub prd: String,
    /// Current task to execute
    pub task: String,
    /// Previous context/iterations
    pub context: Vec<String>,
    /// Maximum tokens to generate
    pub max_tokens: Option<usize>,
}

/// Response from LLM provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    /// Content generated by LLM
    pub content: String,
    /// Tokens used for this request
    pub tokens_used: u32,
    /// Tasks suggested by LLM to create
    pub suggested_tasks: Vec<SuggestedTask>,
    /// Commands extracted from LLM response
    pub commands: Vec<String>,
}

/// Suggested task from LLM response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuggestedTask {
    /// Task title
    pub title: String,
    /// Task description
    pub description: String,
    /// Task priority (higher = more important)
    pub priority: i32,
}

/// Extract suggested tasks from LLM response content
///
/// Parses <TASKS>...</TASKS> tags containing a JSON array of task objects.
/// Returns None if tags are missing.
///
/// # Arguments
/// * `content` - LLM response content to parse
///
/// # Returns
/// Option<Vec<SuggestedTask>> - Parsed tasks or None if tags not found
pub fn parse_suggested_tasks(content: &str) -> Option<Vec<SuggestedTask>> {
    let start_tag = "<TASKS>";
    let end_tag = "</TASKS>";

    let start_idx = content.find(start_tag)?;
    let end_idx = content.find(end_tag)?;

    if start_idx >= end_idx {
        return None;
    }

    let json_str = &content[start_idx + start_tag.len()..end_idx];

    serde_json::from_str::<Vec<SuggestedTask>>(json_str).ok()
}

/// Extract commands from LLM response content
///
/// Parses all <CMD>...</CMD> tags and returns their content.
/// Returns None if no tags are found.
///
/// # Arguments
/// * `content` - LLM response content to parse
///
/// # Returns
/// Option<Vec<String>> - Extracted commands or None if no tags found
pub fn parse_commands(content: &str) -> Option<Vec<String>> {
    let start_tag = "<CMD>";
    let end_tag = "</CMD>";

    let mut commands = Vec::new();
    let mut search_start = 0;

    while let Some(start_idx) = content[search_start..].find(start_tag) {
        let start_absolute = search_start + start_idx;
        let content_start = start_absolute + start_tag.len();

        let end_idx = match content[content_start..].find(end_tag) {
            Some(idx) => idx,
            None => break,
        };

        let end_absolute = content_start + end_idx;
        let command = content[content_start..end_absolute].trim().to_string();
        commands.push(command);

        search_start = end_absolute + end_tag.len();
    }

    if commands.is_empty() {
        None
    } else {
        Some(commands)
    }
}

/// Trait for LLM provider implementations
#[async_trait]
pub trait LLMProviderTrait: Send + Sync {
    /// Complete a request to the LLM
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse>;
}

/// Anthropic Claude LLM provider
pub struct ClaudeProvider {
    client: Client,
}

impl ClaudeProvider {
    /// Create a new ClaudeProvider with an API key
    ///
    /// # Arguments
    /// * `api_key` - Anthropic API key
    pub fn new(api_key: String) -> anyhow::Result<Self> {
        let client = Client::builder()
            .api_key(&api_key)
            .model(Model::Claude35Sonnet20241022)
            .build()?;
        Ok(Self { client })
    }

    /// Build a system prompt from PRD and context
    fn build_system_prompt(&self, prd: &str, context: &[String]) -> String {
        let mut prompt = String::from("# Project PRD\n");
        prompt.push_str(prd);
        prompt.push_str("\n\n");

        if !context.is_empty() {
            prompt.push_str("# Context\n");
            for (i, ctx) in context.iter().enumerate() {
                prompt.push_str(&format!("## Iteration {}\n{}\n\n", i + 1, ctx));
            }
        }

        prompt
    }
}

#[async_trait]
impl LLMProviderTrait for ClaudeProvider {
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse> {
        let system_prompt = self.build_system_prompt(&request.prd, &request.context);

        let mut chat_builder = self.client.chat_builder().system(&system_prompt);

        for ctx in &request.context {
            chat_builder = chat_builder.user_message(ContentBlock::text(ctx));
        }

        chat_builder = chat_builder.user_message(ContentBlock::text(&request.task));

        let chat_request = chat_builder.build();
        let response = self.client.execute_chat(chat_request).await?;

        let content: String = response
            .content
            .iter()
            .filter_map(|block| {
                if let ContentBlock::Text { text, .. } = block {
                    Some(text.clone())
                } else {
                    None
                }
            })
            .collect();

        let tokens_used = response.usage.input_tokens + response.usage.output_tokens;

        Ok(LLMResponse {
            content,
            tokens_used,
            suggested_tasks: vec![],
            commands: vec![],
        })
    }
}

/// OpenAI LLM provider
pub struct OpenAIProvider {
    client: OpenAIClient<OpenAIConfig>,
}

impl OpenAIProvider {
    /// Create a new OpenAIProvider with an API key
    ///
    /// # Arguments
    /// * `api_key` - OpenAI API key
    pub fn new(api_key: String) -> anyhow::Result<Self> {
        let client = OpenAIClient::with_config(OpenAIConfig::new().with_api_key(api_key));
        Ok(Self { client })
    }

    /// Build a system prompt from PRD and context
    fn build_system_prompt(&self, prd: &str, context: &[String]) -> String {
        let mut prompt = String::from("# Project PRD\n");
        prompt.push_str(prd);
        prompt.push_str("\n\n");

        if !context.is_empty() {
            prompt.push_str("# Context\n");
            for (i, ctx) in context.iter().enumerate() {
                prompt.push_str(&format!("## Iteration {}\n{}\n\n", i + 1, ctx));
            }
        }

        prompt
    }
}

#[async_trait]
impl LLMProviderTrait for OpenAIProvider {
    async fn complete(&self, request: &LLMRequest) -> anyhow::Result<LLMResponse> {
        use async_openai::types::{
            ChatCompletionRequestSystemMessage, ChatCompletionRequestUserMessage,
        };

        let system_prompt = self.build_system_prompt(&request.prd, &request.context);

        let mut messages: Vec<ChatCompletionRequestMessage> =
            vec![ChatCompletionRequestSystemMessage::from(system_prompt.as_str()).into()];

        for ctx in &request.context {
            messages.push(ChatCompletionRequestUserMessage::from(ctx.as_str()).into());
        }

        messages.push(ChatCompletionRequestUserMessage::from(request.task.as_str()).into());

        let max_tokens = request.max_tokens.unwrap_or_default() as u32;

        let chat_request = CreateChatCompletionRequestArgs::default()
            .max_tokens(max_tokens)
            .messages(messages)
            .build()?;

        let response = self.client.chat().create(chat_request).await?;

        let content = response
            .choices
            .first()
            .and_then(|choice| choice.message.content.as_ref())
            .ok_or_else(|| anyhow::anyhow!("No content in response"))?
            .clone();

        let usage = response
            .usage
            .ok_or_else(|| anyhow::anyhow!("No usage information in response"))?;
        let tokens_used = usage.total_tokens as u32;

        Ok(LLMResponse {
            content,
            tokens_used,
            suggested_tasks: vec![],
            commands: vec![],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_suggested_tasks_valid() {
        let content = r#"
            Some text here
            <TASKS>[
                {"title": "Add tests", "description": "Write unit tests", "priority": 5},
                {"title": "Fix bug", "description": "Fix authentication bug", "priority": 10}
            ]</TASKS>
            More text
        "#;

        let tasks = parse_suggested_tasks(content);

        assert!(tasks.is_some());
        let tasks = tasks.unwrap();
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].title, "Add tests");
        assert_eq!(tasks[0].description, "Write unit tests");
        assert_eq!(tasks[0].priority, 5);
        assert_eq!(tasks[1].title, "Fix bug");
        assert_eq!(tasks[1].description, "Fix authentication bug");
        assert_eq!(tasks[1].priority, 10);
    }

    #[test]
    fn test_parse_suggested_tasks_missing_tags() {
        let content = "Some content without task tags";

        let tasks = parse_suggested_tasks(content);

        assert!(tasks.is_none());
    }

    #[test]
    fn test_parse_suggested_tasks_malformed_json() {
        let content = r#"
            <TASKS>{ invalid json }</TASKS>
        "#;

        let tasks = parse_suggested_tasks(content);

        assert!(tasks.is_none());
    }

    #[test]
    fn test_parse_suggested_tasks_empty_array() {
        let content = "<TASKS>[]</TASKS>";

        let tasks = parse_suggested_tasks(content);

        assert!(tasks.is_some());
        let tasks = tasks.unwrap();
        assert!(tasks.is_empty());
    }

    #[test]
    fn test_parse_commands_multiple() {
        let content = r#"
            Execute these commands:
            <CMD>cargo build</CMD>
            <CMD>cargo test</CMD>
            <CMD>cargo clippy</CMD>
            Done
        "#;

        let commands = parse_commands(content);

        assert!(commands.is_some());
        let commands = commands.unwrap();
        assert_eq!(commands.len(), 3);
        assert_eq!(commands[0], "cargo build");
        assert_eq!(commands[1], "cargo test");
        assert_eq!(commands[2], "cargo clippy");
    }

    #[test]
    fn test_parse_commands_missing_tags() {
        let content = "Some content without command tags";

        let commands = parse_commands(content);

        assert!(commands.is_none());
    }

    #[test]
    fn test_parse_commands_single() {
        let content = "Run this: <CMD>echo hello</CMD>";

        let commands = parse_commands(content);

        assert!(commands.is_some());
        let commands = commands.unwrap();
        assert_eq!(commands.len(), 1);
        assert_eq!(commands[0], "echo hello");
    }

    #[test]
    fn test_parse_commands_with_whitespace() {
        let content = "<CMD>
            cargo build
        </CMD>";

        let commands = parse_commands(content);

        assert!(commands.is_some());
        let commands = commands.unwrap();
        assert_eq!(commands.len(), 1);
        assert_eq!(commands[0], "cargo build");
    }

    #[test]
    fn test_parse_commands_nested_tags() {
        let content = "<CMD>echo <TAG>test</TAG></CMD>";

        let commands = parse_commands(content);

        assert!(commands.is_some());
        let commands = commands.unwrap();
        assert_eq!(commands.len(), 1);
        assert_eq!(commands[0], "echo <TAG>test</TAG>");
    }

    #[test]
    fn test_llm_request_serialization() {
        let request = LLMRequest {
            prd: "Build a web server".to_string(),
            task: "Create HTTP handler".to_string(),
            context: vec!["Previous task completed".to_string()],
            max_tokens: Some(1000),
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.prd, request.prd);
        assert_eq!(deserialized.task, request.task);
        assert_eq!(deserialized.context, request.context);
        assert_eq!(deserialized.max_tokens, request.max_tokens);
    }

    #[test]
    fn test_llm_response_serialization() {
        let response = LLMResponse {
            content: "Here's the code".to_string(),
            tokens_used: 500,
            suggested_tasks: vec![SuggestedTask {
                title: "Add tests".to_string(),
                description: "Write unit tests".to_string(),
                priority: 5,
            }],
            commands: vec!["cargo test".to_string()],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.content, response.content);
        assert_eq!(deserialized.tokens_used, response.tokens_used);
        assert_eq!(
            deserialized.suggested_tasks.len(),
            response.suggested_tasks.len()
        );
        assert_eq!(deserialized.commands.len(), response.commands.len());
    }

    #[test]
    fn test_suggested_task_serialization() {
        let task = SuggestedTask {
            title: "Fix bug".to_string(),
            description: "Fix the bug in handler".to_string(),
            priority: 10,
        };

        let json = serde_json::to_string(&task).unwrap();
        let deserialized: SuggestedTask = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.title, task.title);
        assert_eq!(deserialized.description, task.description);
        assert_eq!(deserialized.priority, task.priority);
    }

    #[test]
    fn test_llm_request_without_max_tokens() {
        let request = LLMRequest {
            prd: "Test".to_string(),
            task: "Task".to_string(),
            context: vec![],
            max_tokens: None,
        };

        let json = serde_json::to_string(&request).unwrap();
        let deserialized: LLMRequest = serde_json::from_str(&json).unwrap();

        assert!(deserialized.max_tokens.is_none());
    }

    #[test]
    fn test_empty_collections_in_response() {
        let response = LLMResponse {
            content: "Content".to_string(),
            tokens_used: 100,
            suggested_tasks: vec![],
            commands: vec![],
        };

        let json = serde_json::to_string(&response).unwrap();
        let deserialized: LLMResponse = serde_json::from_str(&json).unwrap();

        assert!(deserialized.suggested_tasks.is_empty());
        assert!(deserialized.commands.is_empty());
    }

    #[test]
    fn test_claude_provider_build_system_prompt_with_context() {
        let provider =
            ClaudeProvider::new("sk-ant-api03-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a web server";
        let context = vec![
            "Iteration 1: Created HTTP handler".to_string(),
            "Iteration 2: Added authentication".to_string(),
        ];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a web server"));
        assert!(prompt.contains("# Context"));
        assert!(prompt.contains("Iteration 1: Created HTTP handler"));
        assert!(prompt.contains("Iteration 2: Added authentication"));
    }

    #[test]
    fn test_claude_provider_build_system_prompt_without_context() {
        let provider =
            ClaudeProvider::new("sk-ant-api03-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a CLI tool";
        let context = vec![];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a CLI tool"));
        assert!(!prompt.contains("# Context"));
    }

    #[tokio::test]
    #[ignore = "Requires ANTHROPIC_API_KEY environment variable"]
    async fn test_claude_provider_integration() {
        let api_key = std::env::var("ANTHROPIC_API_KEY")
            .expect("ANTHROPIC_API_KEY must be set for integration test");

        let provider = ClaudeProvider::new(api_key).unwrap();
        let request = LLMRequest {
            prd: "Build a simple calculator".to_string(),
            task: "What is 2 + 2?".to_string(),
            context: vec![],
            max_tokens: Some(100),
        };

        let result = provider.complete(&request).await.unwrap();

        assert!(!result.content.is_empty());
        assert!(result.tokens_used > 0);
        assert!(result.suggested_tasks.is_empty());
        assert!(result.commands.is_empty());
    }

    #[test]
    fn test_openai_provider_build_system_prompt_with_context() {
        let provider = OpenAIProvider::new("sk-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a web server";
        let context = vec![
            "Iteration 1: Created HTTP handler".to_string(),
            "Iteration 2: Added authentication".to_string(),
        ];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a web server"));
        assert!(prompt.contains("# Context"));
        assert!(prompt.contains("Iteration 1: Created HTTP handler"));
        assert!(prompt.contains("Iteration 2: Added authentication"));
    }

    #[test]
    fn test_openai_provider_build_system_prompt_without_context() {
        let provider = OpenAIProvider::new("sk-test-key-for-testing".to_string()).unwrap();
        let prd = "Build a CLI tool";
        let context = vec![];

        let prompt = provider.build_system_prompt(prd, &context);

        assert!(prompt.contains("# Project PRD"));
        assert!(prompt.contains("Build a CLI tool"));
        assert!(!prompt.contains("# Context"));
    }

    #[tokio::test]
    #[ignore = "Requires OPENAI_API_KEY environment variable"]
    async fn test_openai_provider_integration() {
        let api_key = std::env::var("OPENAI_API_KEY")
            .expect("OPENAI_API_KEY must be set for integration test");

        let provider = OpenAIProvider::new(api_key).unwrap();
        let request = LLMRequest {
            prd: "Build a simple calculator".to_string(),
            task: "What is 2 + 2?".to_string(),
            context: vec![],
            max_tokens: Some(100),
        };

        let result = provider.complete(&request).await.unwrap();

        assert!(!result.content.is_empty());
        assert!(result.tokens_used > 0);
        assert!(result.suggested_tasks.is_empty());
        assert!(result.commands.is_empty());
    }
}
